const String = {
    heading : 'Work To Do',
    headingBottom:'App to create your daily to do list',
    login:'Login',
    userName:'User Name',
    password:'Password',
    signupMessage:'Create Account',
    signUp:'Sign Up',
    save:'Save',
    userCreated:'User created successfully',
    addToDo:'Add To Do',
    enterWork:'Enter Work',
    toDoAdded:'To do Added',
    home:'Home',
    userNotExist:'User does not exist',
    enterValues:'Please enter values',
    updateTodo:'Update To Do',
    enterNewValue:'Enter new value',
    updatedValue:'Work updated',
    enterDesc:'Enter description',
    cancel:'Cancel',
    update:'Update',
    description:'Description',
    toDoList:'To Do List',
    listAll:'List All',
    deleteAll:'Delete All',
    clearCache:'Clear Cache',
    logout:'Logout',
    date:'DATE:',
    listAllTodo:'List Of All To Do',
    enterUserName:'*Please enter username',
    enterPassword:'*Please enter password',
    enterWork:'*Please enter work'
}

export default String