const String = {
    heading : 'Work To Do',
    headingBottom:'App to create your daily to do list',
    login:'Login',
    userName:'User Name',
    password:'Password',
    signupMessage:'Create Account',
    signUp:'Sign Up',
    save:'Save',
    userCreated:'User created successfully',
    addToDo:'Add To Do',
    enterWork:'Enter Work',
    toDoAdded:'To do Added',
    home:'Home',
    userNotExist:'User does not exist',
    enterValues:'Please enter values',
    updateTodo:'Update To Do',
    enterNewValue:'Enter new value',
    updatedValue:'Work updated',
    enterDesc:'Enter description',
    cancel:'Cancel',
    update:'Update',
    description:'Description',
    toDoList:'To Do List',
    listAll:'List All',
    deleteAll:'Delete All',
    clearCache:'Clear Cache',
    editUser:'Edit User',
    logout:'Logout',
    date:'DATE:',
    listAllTodo:'List Of All To Do',
    enterUserName:'*Please enter username',
    enterPassword:'*Please enter password',
    enterWork:'Enter work',
    termsConditions:'Do you agree to our terms and conditions',
    selectImage:'Select Image',
    male:'Male',
    female:'Female',
    selectCountry:'Select Country',
    onboarding:'Welcome',
    welcome:'Welcome to To do App !. This app will help you manage daily work tasks and keep track of them',
    loadingData:'Loading data please wait...',
    syncData:'Sync Data',
    userUpated:'User updated successfully',
    ok:'Ok',
    deleteSure:'Are you sure you want to delete ?',
    confirm:'Confirm',
    work:'Work',
    listScreen:'List Screen',
    menu:'Menu',
    menuDesc:'This is main menu screen use it edit your preferences',
    startUsing:'Start Using',
    startUsingDesc:'Isn\'t it Beautiful App! Proceed to start using'
    
}

export default String